seed: ~
#ablation: random_aug # random_aug
aug_prob: 0.5
epochs: &epochs 500
penalty_lambda: 0.2
model_grad_clip: 4.0
auger_grad_clip: 0.002
init_model: False
ckpt_path: ~

data:
    batch_size: 128
    name: &set_name _EMI_ratio0.5
    kwargs:
        set_name: *set_name
        tensor_data_root_path: /content/drive/MyDrive/datasets/UCRTensorData_CEEM

model:
    name: MLP # LSTM, Res18, LF, MLP, MBV2
    kwargs:
#        input_size: [auto assigned]
#        num_classes: [auto assigned]
        base_hidden_dim: 200
        num_layers: 4
auger:
    kwargs:
        ~

model_op:
    name: sgd
    kwargs:
#        params: [auto assigned]
#        lr: [auto assigned]
        weight_decay: 0
model_sc:
    name: plateau       # const, cos, plateau
    kwargs:
        mode: min
        max_lr: 2e-4
        epochs: *epochs
        min_lr: 1e-6
        patience_ratio: 0.03


auger_op:
    name: adam
    kwargs:
#        params: [auto assigned]
#        lr: [auto assigned]
        weight_decay: 0
auger_sc:
    name: cos         # const, cos, plateau
    kwargs:
        max_lr: 1e-4
        epochs: *epochs





